included:
  - Sources
  - Tests

type_name:
  max_length: 42

identifier_name:
  max_length: 44
  excluded: [
        # used in algorithms
	'a', 'b', 'c', 'd', 'e', 'i', 'j', 'f', 
        'k', 'm', 'n', 'o', 'p', 's', 'r', 't', 'v',
	'lm', 'rl', 'ud', 'rd', 'fb', 'l1',
        # cubing terminology
	'U',
	'R',
	'F',
	'D', 
	'L', 
	'B',
	'UR', 'UF', 'UL', 'UB',
	'DR', 'DF', 'DL', 'DB',
	'FR', 'FL', 'BL', 'BR',
        'U1', 'U2', 'U3', 'U4', 'U5', 'U6', 'U7', 'U8', 'U9',
	'R1', 'R2', 'R3', 'R4', 'R5', 'R6', 'R7', 'R8', 'R9',
	'F1', 'F2', 'F3', 'F4', 'F5', 'F6', 'F7', 'F8', 'F9',
	'D1', 'D2', 'D3', 'D4', 'D5', 'D6', 'D7', 'D8', 'D9',
	'L1', 'L2', 'L3', 'L4', 'L5', 'L6', 'L7', 'L8', 'L9',
	'B1', 'B2', 'B3', 'B4', 'B5', 'B6', 'B7', 'B8', 'B9',
	'Ux1', 'Ux2', 'Ux3',
        'Rx1', 'Rx2', 'Rx3',
        'Fx1', 'Fx2', 'Fx3',
        'Dx1', 'Dx2', 'Dx3',
        'Lx1', 'Lx2', 'Lx3',
        'Bx1', 'Bx2', 'Bx3',
        # cubing data
	'ca', 'ea', 'eo', 'co', 'ep', 'cp',
        # general
	'^id$'
  ]
trailing_comma:
  mandatory_comma: true

disabled_rules:
  - opening_brace

